### ISSUE TITLE
merge GIS2BIM into trails

### ISSUE THREAD

**Issue by allanlaal** [DutchSailor/FOSS-BIM-Experiments#1]
@joelgraff @DutchSailor you discussed merging [GIS2BIM](https://github.com/DutchSailor/FOSS-BIM-Experiments/tree/main/GIS2BIM) into [trails](https://github.com/joelgraff/freecad.trails), hows that coming along? can I help? :)

**Comment by allanlaal** [comment]
https://github.com/joelgraff/freecad.trails/issues/84

**Comment by DutchSailor** [comment]
PR is merged, WFS and other functions will follow soon!
